#release configuration
#Tue Jun 02 11:48:05 EDT 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.janelia.saalfeldlab\:sam-link=1.0.1-SNAPSHOT
project.rel.org.janelia.saalfeldlab\:sam-link=1.0.0
project.scm.org.janelia.saalfeldlab\:sam-link.connection=scm\:git\:https\://github.com/saalfeldlab/sam-link
project.scm.org.janelia.saalfeldlab\:sam-link.developerConnection=scm\:git\:git@github.com\:saalfeldlab/sam-link
project.scm.org.janelia.saalfeldlab\:sam-link.tag=HEAD
project.scm.org.janelia.saalfeldlab\:sam-link.url=https\://github.com/saalfeldlab/sam-link
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=sam-link-1.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/saalfeldlab/sam-link
